### ISSUE TITLE
Landing page 

### ISSUE THREAD

**Issue by cappamuzan123** [boney-10/FrankHub#6]

**Comment by boney-10** [comment]
tell me what the problem is?

**Comment by boney-10** [comment]
now*

**Comment by cappamuzan123** [comment]
While creating the landing page I was not able to access the products

**Comment by boney-10** [comment]
No worries, I hope after that we will complete our application for sprint?

**Comment by cappamuzan123** [comment]
Yes

**Comment by boney-10** [comment]
well done! thank you so much for your wonderful contribution
